branches:
  only:
    - master
language: python
python:
    - 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-dev python-libvirt libffi-dev libssl-dev libxml2-dev libxslt1-dev
    - wget http://downloads.sourceforge.net/project/ssdeep/ssdeep-2.12/ssdeep-2.12.tar.gz
    - tar -zxvf ssdeep-2.12.tar.gz
    - cd ssdeep-2.12
    - ./configure && make
    - sudo make install
    - cd ..
install:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install codeclimate-test-reporter
    - pip install nose
    - sudo pip install pyyaml
    #- python setup.py develop
    
before_script: mkdir -p shippable/codecoverage shippable/testresults
script:
    - python utils/community.py -wafb monitor
    - python cuckoo.py --debug --test
    #- coverage run tests/*
    #- py.test --cov=modules tests/*
    #- codeclimate-test-reporter --file .coverage
    #- coverage report -m
    #- nosetests 
    - nosetests --with-coverage --cover-erase --cover-package=./cuckoo
    #- coverage run 
    #- coverage xml -o shippable/codecoverage/coverage.xml
after_success:
  - codeclimate-test-reporter
after_script:
  #- vendor/bin/test-reporter
  #tests --verbose
  - codeclimate-test-reporter