branches:
  only:
    - master
language: python
python:
    - 2.7

install:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install codeclimate-test-reporter
script:
    - python utils/community.py -wafb monitor
    - python cuckoo.py --debug --test
    - coverage run tests/*
    #- py.test --cov=cuckoo tests/*
    #- codeclimate-test-reporter --file .coverage
    #- nosetests --with-coverage 
after_success:
  - codeclimate-test-reporter
after_script:
  #- vendor/bin/test-reporter