branches:
  only:
    - master
language: python
python:
    - 2.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-dev python-libvirt libffi-dev libssl-dev libxml2-dev libxslt1-dev
    - wget http://downloads.sourceforge.net/project/ssdeep/ssdeep-2.12/ssdeep-2.12.tar.gz
    - tar -zxvf ssdeep-2.12.tar.gz
    - cd ssdeep-2.12
    - ./configure && make
    - sudo make install
    - cd ..
install:
    - pip install -r requirements.txt
script:
    - python utils/community.py -wafb monitor
    - python cuckoo.py --debug --test
    #- nosetests
addons:
    code_climate:
        repo_token: 0a165fb4c61446ea00c0ae6ee310b4359678011363d95c8980f7d2e1696b7a73
